services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - smarthome-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  temperature-api:
    build: smart_home/tmpr_api/
    container_name: smarthome-api
    ports:
        - "8081:8081"
    networks:
        - smarthome-network    
        
volumes:
  pgdata:
    driver: local

networks:
  smarthome-network:
    driver: bridge