services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - smarthome-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql # Монтирование скрипта инициализации

  smart-home:
    build: smart_home/tmpr_api/
    container_name: smart-home
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
        - smarthome-network    
        
volumes:
  pgdata:
    driver: local

networks:
  smarthome-network:
    driver: bridge